### ISSUE TITLE
[✨ Feature Request]: raise a more descriptive exception when no queries are defined for a Dataset

### ISSUE THREAD

**Issue by borisrakovan** [LukasZahradnik/PyNeuraLogic#25]
### Is your feature request related to a problem? Please describe.

While familiarizing myself with the framework, I defined a Dataset object and added some examples to it. At first, I forgot to add queries before attempting to call `evaluator.train(dataset, generator=False)` and received the following `NullPointerException`:

```
Py4JJavaError: An error occurred while calling o176.collect.
: java.lang.NullPointerException
at cz.cvut.fel.ida.neural.networks.structure.building.Neuralizer.getQueryMatchingLiterals(Neuralizer.java:250)
at cz.cvut.fel.ida.neural.networks.structure.building.Neuralizer.supervisedNeuralization(Neuralizer.java:171)
at cz.cvut.fel.ida.neural.networks.structure.building.Neuralizer.neuralize(Neuralizer.java:145)
at cz.cvut.fel.ida.pipelines.pipes.specific.SupervisedNeuralizationPipe.lambda$apply$1(SupervisedNeuralizationPipe.java:38)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.base/java.lang.Thread.run(Thread.java:829)
```

### Describe the solution you'd like

A more descriptive error could be raised in case the dataset does not contain any queries. Since it is an exception triggered by the Java backend, it is possible that it should be handled there. In that case, please let me know and I will move this issue to the backend repo.

**Comment by LukasZahradnik** [comment]
Hi, thanks for opening the feature request.
I added checks and more descriptive exceptions for cases with no queries and released them in PyNeuraLogic v0.1.1.

When there are no queries in the queries list (or queries in the example list), it will throw an exception.
